function buildInventoryWorkspacePanels({
  services,
  serviceSearch,
  setServiceSearch,
  startNewService,
  filteredServices,
  isCreatingService,
  selectedServiceId,
  selectService,
  serviceForm,
  onServiceFieldChange,
  saveService,
  serviceSaving,
  canDelete,
  deleteService,
  serviceStatus,
  serviceError,
  materials,
  materialSearch,
  setMaterialSearch,
  startNewMaterial,
  filteredMaterials,
  isCreatingMaterial,
  selectedMaterialId,
  selectMaterial,
  materialForm,
  onMaterialFieldChange,
  saveMaterial,
  materialSaving,
  deleteMaterial,
  materialStatus,
  materialError
}) {
  return {
    servicePanel: {
      services,
      serviceSearch,
      setServiceSearch,
      startNewService,
      filteredServices,
      isCreatingService,
      selectedServiceId,
      selectService,
      serviceForm,
      onServiceFieldChange,
      saveService,
      serviceSaving,
      canDelete,
      deleteService,
      serviceStatus,
      serviceError
    },
    materialPanel: {
      materials,
      materialSearch,
      setMaterialSearch,
      startNewMaterial,
      filteredMaterials,
      isCreatingMaterial,
      selectedMaterialId,
      selectMaterial,
      materialForm,
      onMaterialFieldChange,
      saveMaterial,
      materialSaving,
      canDelete,
      deleteMaterial,
      materialStatus,
      materialError
    }
  };
}

export { buildInventoryWorkspacePanels };
