name: building-company

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: building-company:latest
    env_file:
      - .env
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    restart: unless-stopped
