services:
  app:
    image: building-company:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run migrate && npm start"
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always
