sonar.cpd.exclusions=\
cookie-policy.html,\
privacy.html,\
terms.html,\
premium-*.html,\
interior-renovations-manchester.html,\
client-dashboard.html,\
manager-dashboard.html,\
client-review.html,\
manager-review.html,\
migrations/**/*.js,\
tests/**/*.js
